### ISSUE TITLE
Add ESLint config file

### ISSUE THREAD

**Issue by xredo** [MarsBased/marstyle#1]

**Comment by davidgg** [comment]
@xredo Is this an active request? Are we creating a new ESLint for plain js files?

**Comment by xredo** [comment]
@davidgg Yes!

**Comment by oriolbcn** [comment]
We use ES6 on some Rails projects that don't use Angular, so it's interesting to have style guidelines for those projects too.

**Comment by danigb** [comment]
As you already know, I had a very nice experience with `prettier`. That tool automatically fixes all _style_ and _formatting_ issues (spaces, lines length, ...). One benefit of using that tool is that the eslint configuration is only related to semantic issues, so it's very small and focused. 

So I'm advocating to create a small semantic eslint configuration and promote the use of `prettier` or a similar tool.

**Comment by davidgg** [comment]
@danigb I think it's a good idea the use of prettier with ESLint. But I would like to explore the full range of options of ESLint (except those that are defined by prettier), it has tons of configurations that can avoid common mistakes.

**Comment by davidgg** [comment]
For now on, we will be using eslint and existing preset: `estlint:recommended` for .js files. Check it at https://eslint.org/docs/rules/
