### ISSUE TITLE
Wrong namespaces

### ISSUE THREAD

**Issue by dvdgs88** [MarsBased/marstyle#20]
Style/MultilineOperationIndentation has the wrong namespace - should be Layout
Style/EmptyLinesAroundClassBody has the wrong namespace - should be Layout

**Comment by pablorc** [comment]
Style/VariableNumber has the wrong namespace - should be Naming

**Comment by artero** [comment]
@danigb had a PR about this #22

**Comment by danigb** [comment]
@artero gracias por mencionarlo! Se me pasó referenciar este issue 🤦‍♂️
