### ISSUE TITLE
Remove Double negation check

### ISSUE THREAD

**Issue by xredo** [MarsBased/marstyle#21]
http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/DoubleNegation

The solution suggested to avoid the double negation is not robust enough. Examples like `!false.nil?` would fail for example.

**Comment by oriolbcn** [comment]
agree, I like the "bang bang" pattern.

**Comment by davidgg** [comment]
Is almost the birthday of this one, any action or PR to close it? @xredo

**Comment by xredo** [comment]
@davidgg I have closed it with a commit. Thanks for the notice! 👍
