### ISSUE TITLE
[Typescript] Increase max line length

### ISSUE THREAD

**Issue by davidgg** [MarsBased/marstyle#26]

**Comment by davidgg** [comment]
We have the 80 chars max length limit for typescript. is it enough?

**Comment by oriolbcn** [comment]
I wuould put the same maximum as with Ruby, I think it's 90, so agree to increase it

**Comment by danigb** [comment]
Even I don't like very much the 80 char length limitation, I think that unify all languages will help.

**Comment by dvdgs88** [comment]
+ 1 to 9 limit

**Comment by davidgg** [comment]
closed by e62d945
