### ISSUE TITLE
[Ruby] Change FrozenStringLiteralComment to true

### ISSUE THREAD

**Issue by artero** [MarsBased/marstyle#27]
Change to:
Style/FrozenStringLiteralComment:
  Enabled: true

In ruby 3 all strings were immutables

**Comment by xredo** [comment]
Watch out with this rule. I do agree that we need to add it to our projects to make our apps compatible with Ruby 3, but we need to be aware that after adding this rule we can break our current codebase.

**Comment by oriolbcn** [comment]
Yeah the idea is good but I think Rails is not ready to handle this option yet 😂

**Comment by xredo** [comment]
After reading a little bit more on this I really believe that we need to better discuss this. This can bring looots of bugs to our application. The ones that are difficult to spot. More on this on the next Martian Tapas.

**Comment by oriolbcn** [comment]
We have agreed on including it, so that we start using the frozen_string_literal comment in new projects.

**Comment by davidgg** [comment]
@artero can you confirm that the rule is accepted and therefore the PR? should we merge the PR?

**Comment by artero** [comment]
For me is a good think put this rule. But I suggest adding a comment as a warning for old ruby versions
