### ISSUE TITLE
[proposal] publish this repository as github pages

### ISSUE THREAD

**Issue by danigb** [MarsBased/marstyle#28]
I don't know how are you copying this files in Pathfinder, but if we publish this repository as a github pages we will have URLs to fetch the files directly. We can add links to them in the README.

**Comment by oriolbcn** [comment]
I think it's not necessary. For Rubocop it has a built-in feature to fetch the yml from a repo and for TSLint we have it published as an npm package, which is default way to go.

**Comment by xredo** [comment]
I do agree with Oriol. I think it's enough with the npm package and referencing Rubocop with the raw URL. I am closing this issue for now.
