### ISSUE TITLE
Rails/OutputSafety

### ISSUE THREAD

**Issue by xredo** [MarsBased/marstyle#3]
http://www.rubydoc.info/gems/rubocop/0.41.0/RuboCop/Cop/Rails/OutputSafety

I would vote for removing this. There are certain situations where you need to use html_safe strings in Rails. I believe that people is experienced enough to use it only when dealing with texts not provided by end users.

**Comment by oriolbcn** [comment]
yeah let's remove it, it makes sense to use it sometimes
