### ISSUE TITLE
[Rubocop] Add migration folders to Rubocop exclude folders

### ISSUE THREAD

**Issue by xredo** [MarsBased/marstyle#38]
As migrations are generated automatically with Rails I don't see the point of having them checked with Rubocop.

- 'db/migrate/**/*'

**Comment by xredo** [comment]
@MarsBased/ruby-team Anyone against including this clause?

**Comment by artero** [comment]
I think is necessary, because is usual add on it other code apart from the regular migration code.

**Comment by davidgg** [comment]
any volunteer to create a PR? @artero

**Comment by artero** [comment]
Done PR to close this #47
