### ISSUE TITLE
[RuboCop] Remove PredicateName naming rule

### ISSUE THREAD

**Issue by oriolbcn** [MarsBased/marstyle#42]
By default there is a rule that disallows the use method names like `is_main?` or `has_default?`. Instead it tells you to avoid using the `is_` or `has_` prefix.

For the `is_` I agree it's better to avoid using it, but for `has_` I think it has a different meaning. I usually use it to ask if something contains another something and find it much more clear to have the `has_`.

Since I don't think is worth creating a custom rule based on this one that only disallows the `is_` I propose to remove the rule.

```
Naming/PredicateName:
    Enabled: false
```

**Comment by davidgg** [comment]
@artero @xredo @pablorc @dvdgs88 ideas, PR, suggestions? 😇

**Comment by xredo** [comment]
Agree!
