### ISSUE TITLE
[RuboCop] Remove Style/ClassAndModuleChildren

### ISSUE THREAD

**Issue by oriolbcn** [MarsBased/marstyle#43]
This rule disallows the definition of nested classes and modules using the inline style, like `class User::ExportService; end`.

Since we are using this style for services now, I think we should remove this rule.

```
Style/ClassAndModuleChildren:
  Enabled: false
```

**Comment by davidgg** [comment]
@artero @xredo @pablorc @dvdgs88 ideas, PR, suggestions? 😇

**Comment by xredo** [comment]
Correct me if I am wrong, but I think that we are now using the pluralized way of the module.

So, we don't really need to remove the rule.

**Comment by oriolbcn** [comment]
Yes in the end we decided to go that way, closing.
