### ISSUE TITLE
[RuboCop] Exclude JBuilder from `Style/LambdaCall`

### ISSUE THREAD

**Issue by oriolbcn** [MarsBased/marstyle#44]
JBuilder has this syntax to set attributes of the response: `json.(object, :attr1, :attr2)`.

This makes the `Style/LambdaCall` call fail. We should add an exclusion like this:

```
Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'
```

**Comment by davidgg** [comment]
@artero @xredo @pablorc @dvdgs88 ideas, PR, suggestions? 😇

**Comment by xredo** [comment]
I agree with this one.
